deploy_production:
  stage: deploy
  script:
    - echo "Deploying to production"
    - ssh projet@139.124.86.169 'bash -s' < deployment-script.sh
  only:
    - master  # Déclencher le déploiement uniquement sur la branche master
