version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - client
      - app

  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: new_password
      MYSQL_DATABASE: Users

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_USER: root
      MYSQL_PASSWORD: new_password
      MYSQL_DATABASE: Users
